#!/usr/bin/env bash

echo "🔐 STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}"
echo "🧬 SUPABASE_URL=${SUPABASE_URL}"
echo "🔑 SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}"
echo "🔐 SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}"
echo "🪪 SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}"

echo "🌐 NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}"
echo "🔓 NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}"

echo "🧪 POSTGRES_PRISMA_URL=${POSTGRES_PRISMA_URL}"
echo "🧪 POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}"

echo "🏷️ SITE_NAME=${SITE_NAME}"
echo "🌍 ENVIRONMENT=${ENVIRONMENT}"
